### ISSUE TITLE
Option "Mobile Export Option" interferes with Education Edition's "Classroom Settings" on Resource Packs tab (merges with Classroom Settings and hides its tab)

### ISSUE THREAD

**Issue by nonperforming** [PiSaucer/VanillaTweaksBedrock#5]
I do not have an iOS device for testing this on such device, but I would imagine it would be the same. Exporting from PC/Mac would be done on the World Select screen. Might as well include a warning for such

![image](https://user-images.githubusercontent.com/43197300/154029852-76f3541d-ee8a-49f4-83e2-526a5737a7c8.png)

**Comment by PiSaucer** [comment]
I will look into this. Normally I play on the standard version of Minecraft Bedrock.

**Comment by PiSaucer** [comment]
I don't understand why you need to select this option since it appears to be included in all versions of the education according to [Mojang themselves](https://educommunity.minecraft.net/hc/en-us/articles/360047555391-Importing-and-Exporting-Your-Worlds-). I am missing something? If you could already export the world by the default settings why even both?

**Comment by nonperforming** [comment]
Ahh I just wanted to see lol 😅. This shouldn't be a problem unless
somebody just ticked it going "sure sounds good"

I was thinking maybe there should be a small warning when ticked?

**Comment by PiSaucer** [comment]
I added a warning at the top stating that packs may not work on Education Edition in aca2f316a203777726eb1190863a2f7aea73daae. Also added a warning on the list item in 0cfba809a344f9b3942ac04540f2ff01786e8ccf. Let me know if there are any more Education issues since I don't have that version and feel free to make a fork and merge. I recommend turning on issues within those forked settings.
